-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft32_cordic_circ_apfixed_18_3_0_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    z_read : IN STD_LOGIC_VECTOR (16 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (17 downto 0) );
end;


architecture behav of fft32_cordic_circ_apfixed_18_3_0_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv18_6487 : STD_LOGIC_VECTOR (17 downto 0) := "000110010010000111";
    constant ap_const_lv18_39B79 : STD_LOGIC_VECTOR (17 downto 0) := "111001101101111001";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv18_76B0 : STD_LOGIC_VECTOR (17 downto 0) := "000111011010110000";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv18_3C4A8 : STD_LOGIC_VECTOR (17 downto 0) := "111100010010101000";
    constant ap_const_lv18_3EB6 : STD_LOGIC_VECTOR (17 downto 0) := "000011111010110110";
    constant ap_const_lv18_3E0A5 : STD_LOGIC_VECTOR (17 downto 0) := "111110000010100101";
    constant ap_const_lv18_1FD4 : STD_LOGIC_VECTOR (17 downto 0) := "000001111111010100";
    constant ap_const_lv18_3F016 : STD_LOGIC_VECTOR (17 downto 0) := "111111000000010110";
    constant ap_const_lv18_FFA : STD_LOGIC_VECTOR (17 downto 0) := "000000111111111010";
    constant ap_const_lv18_3F803 : STD_LOGIC_VECTOR (17 downto 0) := "111111100000000011";
    constant ap_const_lv18_7FE : STD_LOGIC_VECTOR (17 downto 0) := "000000011111111110";
    constant ap_const_lv18_3FC01 : STD_LOGIC_VECTOR (17 downto 0) := "111111110000000001";
    constant ap_const_lv18_3FE : STD_LOGIC_VECTOR (17 downto 0) := "000000001111111110";
    constant ap_const_lv18_3FE01 : STD_LOGIC_VECTOR (17 downto 0) := "111111111000000001";
    constant ap_const_lv15_26DD : STD_LOGIC_VECTOR (14 downto 0) := "010011011011101";
    constant ap_const_lv15_7497 : STD_LOGIC_VECTOR (14 downto 0) := "111010010010111";
    constant ap_const_lv16_8B69 : STD_LOGIC_VECTOR (15 downto 0) := "1000101101101001";
    constant ap_const_lv16_26DD : STD_LOGIC_VECTOR (15 downto 0) := "0010011011011101";
    constant ap_const_lv16_D923 : STD_LOGIC_VECTOR (15 downto 0) := "1101100100100011";
    constant ap_const_lv16_7497 : STD_LOGIC_VECTOR (15 downto 0) := "0111010010010111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv18_1FE : STD_LOGIC_VECTOR (17 downto 0) := "000000000111111110";
    constant ap_const_lv18_3FF01 : STD_LOGIC_VECTOR (17 downto 0) := "111111111100000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv18_FE : STD_LOGIC_VECTOR (17 downto 0) := "000000000011111110";
    constant ap_const_lv18_3FF81 : STD_LOGIC_VECTOR (17 downto 0) := "111111111110000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv18_7E : STD_LOGIC_VECTOR (17 downto 0) := "000000000001111110";
    constant ap_const_lv18_3FFC1 : STD_LOGIC_VECTOR (17 downto 0) := "111111111111000001";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv18_3E : STD_LOGIC_VECTOR (17 downto 0) := "000000000000111110";
    constant ap_const_lv18_3FFE1 : STD_LOGIC_VECTOR (17 downto 0) := "111111111111100001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv18_1E : STD_LOGIC_VECTOR (17 downto 0) := "000000000000011110";
    constant ap_const_lv18_3FFF1 : STD_LOGIC_VECTOR (17 downto 0) := "111111111111110001";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv18_E : STD_LOGIC_VECTOR (17 downto 0) := "000000000000001110";
    constant ap_const_lv18_3FFF9 : STD_LOGIC_VECTOR (17 downto 0) := "111111111111111001";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv18_6 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000110";
    constant ap_const_lv18_3FFFD : STD_LOGIC_VECTOR (17 downto 0) := "111111111111111101";
    constant ap_const_lv18_2 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000010";
    constant ap_const_lv18_3FFFF : STD_LOGIC_VECTOR (17 downto 0) := "111111111111111111";
    constant ap_const_lv17_1FFFF : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111111";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_state6_pp0_stage1_iter2 : BOOLEAN;
    signal ap_block_state8_pp0_stage1_iter3 : BOOLEAN;
    signal ap_block_state10_pp0_stage1_iter4 : BOOLEAN;
    signal ap_block_state12_pp0_stage1_iter5 : BOOLEAN;
    signal ap_block_state14_pp0_stage1_iter6 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal tmp_fu_162_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_1808 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_reg_1808_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_1808_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal d_reg_1816 : STD_LOGIC_VECTOR (0 downto 0);
    signal d_reg_1816_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal d_reg_1816_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tz_1_fu_214_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tz_1_reg_1822 : STD_LOGIC_VECTOR (17 downto 0);
    signal d_1_reg_1827 : STD_LOGIC_VECTOR (0 downto 0);
    signal d_1_reg_1827_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal d_1_reg_1827_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_1833 : STD_LOGIC_VECTOR (0 downto 0);
    signal tz_2_fu_248_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tz_2_reg_1838 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal d_2_reg_1843 : STD_LOGIC_VECTOR (0 downto 0);
    signal d_2_reg_1843_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal d_2_reg_1843_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_reg_1849 : STD_LOGIC_VECTOR (0 downto 0);
    signal tz_3_fu_282_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tz_3_reg_1854 : STD_LOGIC_VECTOR (17 downto 0);
    signal d_3_reg_1859 : STD_LOGIC_VECTOR (0 downto 0);
    signal d_3_reg_1859_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal d_3_reg_1859_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1865 : STD_LOGIC_VECTOR (0 downto 0);
    signal tz_4_fu_316_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tz_4_reg_1870 : STD_LOGIC_VECTOR (17 downto 0);
    signal d_4_reg_1875 : STD_LOGIC_VECTOR (0 downto 0);
    signal d_4_reg_1875_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_reg_1881 : STD_LOGIC_VECTOR (0 downto 0);
    signal tz_5_fu_350_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tz_5_reg_1886 : STD_LOGIC_VECTOR (17 downto 0);
    signal d_5_reg_1891 : STD_LOGIC_VECTOR (0 downto 0);
    signal d_5_reg_1891_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_reg_1897 : STD_LOGIC_VECTOR (0 downto 0);
    signal tz_6_fu_384_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tz_6_reg_1902 : STD_LOGIC_VECTOR (17 downto 0);
    signal d_6_reg_1907 : STD_LOGIC_VECTOR (0 downto 0);
    signal d_6_reg_1907_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_reg_1913 : STD_LOGIC_VECTOR (0 downto 0);
    signal tx_2_fu_578_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal tx_2_reg_1918 : STD_LOGIC_VECTOR (16 downto 0);
    signal ty_2_fu_585_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ty_2_reg_1924 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_9_reg_1930 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln98_3_reg_1935 : STD_LOGIC_VECTOR (12 downto 0);
    signal tz_7_fu_624_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tz_7_reg_1940 : STD_LOGIC_VECTOR (17 downto 0);
    signal d_7_reg_1945 : STD_LOGIC_VECTOR (0 downto 0);
    signal d_7_reg_1945_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_reg_1951 : STD_LOGIC_VECTOR (0 downto 0);
    signal tx_4_fu_738_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal tx_4_reg_1956 : STD_LOGIC_VECTOR (16 downto 0);
    signal ty_4_fu_745_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ty_4_reg_1962 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_15_reg_1968 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_16_reg_1973 : STD_LOGIC_VECTOR (10 downto 0);
    signal tz_8_fu_784_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tz_8_reg_1978 : STD_LOGIC_VECTOR (17 downto 0);
    signal d_8_reg_1983 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_reg_1989 : STD_LOGIC_VECTOR (0 downto 0);
    signal tx_6_fu_898_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal tx_6_reg_1994 : STD_LOGIC_VECTOR (16 downto 0);
    signal ty_6_fu_905_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ty_6_reg_2000 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_23_reg_2006 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_24_reg_2011 : STD_LOGIC_VECTOR (8 downto 0);
    signal tz_9_fu_944_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tz_9_reg_2016 : STD_LOGIC_VECTOR (17 downto 0);
    signal d_9_reg_2021 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_reg_2027 : STD_LOGIC_VECTOR (0 downto 0);
    signal tx_8_fu_1058_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal tx_8_reg_2032 : STD_LOGIC_VECTOR (16 downto 0);
    signal ty_8_fu_1065_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ty_8_reg_2038 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_31_reg_2044 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_32_reg_2049 : STD_LOGIC_VECTOR (6 downto 0);
    signal tz_10_fu_1104_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tz_10_reg_2054 : STD_LOGIC_VECTOR (17 downto 0);
    signal d_10_reg_2059 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_37_reg_2065 : STD_LOGIC_VECTOR (0 downto 0);
    signal tx_10_fu_1218_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal tx_10_reg_2070 : STD_LOGIC_VECTOR (16 downto 0);
    signal ty_10_fu_1225_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ty_10_reg_2076 : STD_LOGIC_VECTOR (16 downto 0);
    signal tz_11_fu_1244_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tz_11_reg_2082 : STD_LOGIC_VECTOR (17 downto 0);
    signal d_11_reg_2087 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_39_reg_2093 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_40_reg_2098 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_41_reg_2103 : STD_LOGIC_VECTOR (0 downto 0);
    signal tz_12_fu_1338_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tz_12_reg_2108 : STD_LOGIC_VECTOR (17 downto 0);
    signal tx_12_fu_1404_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal tx_12_reg_2113 : STD_LOGIC_VECTOR (16 downto 0);
    signal ty_12_fu_1412_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ty_12_reg_2119 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_45_reg_2125 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_47_reg_2130 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_48_reg_2135 : STD_LOGIC_VECTOR (2 downto 0);
    signal tz_13_fu_1460_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tz_13_reg_2140 : STD_LOGIC_VECTOR (17 downto 0);
    signal tx_13_fu_1500_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal tx_13_reg_2145 : STD_LOGIC_VECTOR (16 downto 0);
    signal ty_13_fu_1508_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ty_13_reg_2151 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_49_reg_2157 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_51_reg_2162 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_52_reg_2167 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal sext_ln79_fu_158_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tmp_fu_162_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln101_fu_170_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln79_fu_158_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal tz_fu_178_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_2_fu_192_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln94_fu_208_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln94_1_fu_200_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal add_ln94_2_fu_243_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln94_3_fu_236_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln94_4_fu_277_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln94_5_fu_270_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln94_6_fu_311_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln94_7_fu_304_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln94_8_fu_345_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln94_9_fu_338_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln94_10_fu_379_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln94_11_fu_372_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln102_fu_406_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln107_fu_420_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tx_fu_434_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln103_fu_413_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln108_fu_427_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ty_fu_445_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_s_fu_456_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln98_1_fu_470_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln94_fu_441_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln102_fu_480_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln94_fu_452_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln84_fu_466_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln102_fu_484_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln107_fu_496_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tx_1_fu_508_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln103_fu_490_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln108_fu_502_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_6_fu_526_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal ty_1_fu_519_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln98_2_fu_540_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln94_1_fu_515_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln102_1_fu_550_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln84_1_fu_536_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln102_1_fu_554_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln107_1_fu_566_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln103_1_fu_560_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln108_1_fu_572_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln94_12_fu_619_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln94_13_fu_612_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln102_2_fu_649_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln84_fu_646_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln102_2_fu_652_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln107_2_fu_662_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln103_2_fu_657_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln108_2_fu_667_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tx_3_fu_672_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_12_fu_686_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal ty_3_fu_679_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln98_4_fu_700_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln102_3_fu_710_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln84_1_fu_696_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln102_3_fu_714_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln107_3_fu_726_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln103_3_fu_720_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln108_3_fu_732_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln94_14_fu_779_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln94_15_fu_772_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln84_3_fu_809_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln84_2_fu_806_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln102_4_fu_812_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln107_4_fu_822_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln103_4_fu_817_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln108_4_fu_827_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tx_5_fu_832_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_19_fu_846_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal ty_5_fu_839_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_20_fu_860_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln84_5_fu_870_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln84_4_fu_856_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln102_5_fu_874_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln107_5_fu_886_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln103_5_fu_880_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln108_5_fu_892_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln94_16_fu_939_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln94_17_fu_932_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln84_7_fu_969_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln84_6_fu_966_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln102_6_fu_972_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln107_6_fu_982_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln103_6_fu_977_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln108_6_fu_987_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tx_7_fu_992_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_27_fu_1006_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ty_7_fu_999_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_28_fu_1020_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln84_9_fu_1030_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln84_8_fu_1016_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln102_7_fu_1034_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln107_7_fu_1046_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln103_7_fu_1040_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln108_7_fu_1052_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln94_18_fu_1099_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln94_19_fu_1092_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln84_11_fu_1129_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln84_10_fu_1126_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln102_8_fu_1132_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln107_8_fu_1142_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln103_8_fu_1137_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln108_8_fu_1147_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tx_9_fu_1152_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_35_fu_1166_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal ty_9_fu_1159_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_36_fu_1180_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln84_13_fu_1190_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln84_12_fu_1176_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln102_9_fu_1194_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln107_9_fu_1206_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln103_9_fu_1200_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln108_9_fu_1212_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln94_20_fu_1239_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln94_21_fu_1232_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln84_15_fu_1289_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln84_14_fu_1286_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln102_10_fu_1292_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln107_10_fu_1302_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln103_10_fu_1297_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln108_10_fu_1307_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln94_22_fu_1333_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln94_23_fu_1326_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal tx_11_fu_1312_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_43_fu_1352_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ty_11_fu_1319_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_44_fu_1366_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln84_17_fu_1376_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln84_16_fu_1362_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal d_12_fu_1344_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln102_11_fu_1380_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln107_11_fu_1392_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln103_11_fu_1386_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln108_11_fu_1398_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln94_24_fu_1455_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln94_25_fu_1448_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln84_19_fu_1477_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln84_18_fu_1474_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal d_13_fu_1466_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln102_12_fu_1480_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln107_12_fu_1490_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln103_12_fu_1485_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln108_12_fu_1495_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln94_26_fu_1551_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln94_27_fu_1544_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal tz_14_fu_1556_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln84_21_fu_1573_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln84_20_fu_1570_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln102_13_fu_1576_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_53_fu_1586_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln103_13_fu_1581_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_54_fu_1602_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln84_1_fu_1610_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln84_fu_1594_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln102_14_fu_1618_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_55_fu_1630_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln103_14_fu_1624_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_56_fu_1646_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln84_3_fu_1654_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln84_2_fu_1638_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln107_13_fu_1674_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_57_fu_1684_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln108_13_fu_1679_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_58_fu_1700_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln107_1_fu_1708_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln98_fu_1692_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln107_14_fu_1716_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal x_s_1_fu_1728_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln108_14_fu_1722_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal y_s_fu_1744_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln107_2_fu_1752_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln98_1_fu_1736_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal d_14_fu_1562_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln102_15_fu_1662_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln107_15_fu_1760_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tx_14_fu_1772_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln103_15_fu_1668_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln108_15_fu_1766_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal ty_14_fu_1784_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln94_1_fu_1780_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln83_fu_1792_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to6 : STD_LOGIC;
    signal ap_idle_pp0_0to5 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                d_10_reg_2059 <= tz_10_fu_1104_p2(17 downto 17);
                d_2_reg_1843 <= tz_2_fu_248_p2(17 downto 17);
                d_2_reg_1843_pp0_iter1_reg <= d_2_reg_1843;
                d_2_reg_1843_pp0_iter2_reg <= d_2_reg_1843_pp0_iter1_reg;
                d_4_reg_1875 <= tz_4_fu_316_p2(17 downto 17);
                d_4_reg_1875_pp0_iter2_reg <= d_4_reg_1875;
                d_6_reg_1907 <= tz_6_fu_384_p2(17 downto 17);
                d_6_reg_1907_pp0_iter3_reg <= d_6_reg_1907;
                d_8_reg_1983 <= tz_8_fu_784_p2(17 downto 17);
                tmp_13_reg_1881 <= tz_4_fu_316_p2(17 downto 17);
                tmp_15_reg_1968 <= tx_4_fu_738_p3(16 downto 6);
                tmp_16_reg_1973 <= ty_4_fu_745_p3(16 downto 6);
                tmp_21_reg_1913 <= tz_6_fu_384_p2(17 downto 17);
                tmp_29_reg_1989 <= tz_8_fu_784_p2(17 downto 17);
                tmp_31_reg_2044 <= tx_8_fu_1058_p3(16 downto 10);
                tmp_32_reg_2049 <= ty_8_fu_1065_p3(16 downto 10);
                tmp_37_reg_2065 <= tz_10_fu_1104_p2(17 downto 17);
                tmp_45_reg_2125 <= tz_12_fu_1338_p2(17 downto 17);
                tmp_47_reg_2130 <= tx_12_fu_1404_p3(16 downto 14);
                tmp_48_reg_2135 <= ty_12_fu_1412_p3(16 downto 14);
                tmp_7_reg_1849 <= tz_2_fu_248_p2(17 downto 17);
                tx_12_reg_2113 <= tx_12_fu_1404_p3;
                tx_4_reg_1956 <= tx_4_fu_738_p3;
                tx_8_reg_2032 <= tx_8_fu_1058_p3;
                ty_12_reg_2119 <= ty_12_fu_1412_p3;
                ty_4_reg_1962 <= ty_4_fu_745_p3;
                ty_8_reg_2038 <= ty_8_fu_1065_p3;
                tz_10_reg_2054 <= tz_10_fu_1104_p2;
                tz_12_reg_2108 <= tz_12_fu_1338_p2;
                tz_2_reg_1838 <= tz_2_fu_248_p2;
                tz_4_reg_1870 <= tz_4_fu_316_p2;
                tz_6_reg_1902 <= tz_6_fu_384_p2;
                tz_8_reg_1978 <= tz_8_fu_784_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                d_11_reg_2087 <= tz_11_fu_1244_p2(17 downto 17);
                d_1_reg_1827 <= tz_1_fu_214_p2(17 downto 17);
                d_1_reg_1827_pp0_iter1_reg <= d_1_reg_1827;
                d_1_reg_1827_pp0_iter2_reg <= d_1_reg_1827_pp0_iter1_reg;
                d_3_reg_1859 <= tz_3_fu_282_p2(17 downto 17);
                d_3_reg_1859_pp0_iter2_reg <= d_3_reg_1859;
                d_3_reg_1859_pp0_iter3_reg <= d_3_reg_1859_pp0_iter2_reg;
                d_5_reg_1891 <= tz_5_fu_350_p2(17 downto 17);
                d_5_reg_1891_pp0_iter3_reg <= d_5_reg_1891;
                d_7_reg_1945 <= tz_7_fu_624_p2(17 downto 17);
                d_7_reg_1945_pp0_iter4_reg <= d_7_reg_1945;
                d_9_reg_2021 <= tz_9_fu_944_p2(17 downto 17);
                d_reg_1816 <= tz_fu_178_p2(17 downto 17);
                d_reg_1816_pp0_iter1_reg <= d_reg_1816;
                d_reg_1816_pp0_iter2_reg <= d_reg_1816_pp0_iter1_reg;
                tmp_10_reg_1865 <= tz_3_fu_282_p2(17 downto 17);
                tmp_17_reg_1897 <= tz_5_fu_350_p2(17 downto 17);
                tmp_23_reg_2006 <= tx_6_fu_898_p3(16 downto 8);
                tmp_24_reg_2011 <= ty_6_fu_905_p3(16 downto 8);
                tmp_25_reg_1951 <= tz_7_fu_624_p2(17 downto 17);
                tmp_33_reg_2027 <= tz_9_fu_944_p2(17 downto 17);
                tmp_39_reg_2093 <= tx_10_fu_1218_p3(16 downto 12);
                tmp_40_reg_2098 <= ty_10_fu_1225_p3(16 downto 12);
                tmp_41_reg_2103 <= tz_11_fu_1244_p2(17 downto 17);
                tmp_49_reg_2157 <= tz_13_fu_1460_p2(17 downto 17);
                tmp_4_reg_1833 <= tz_1_fu_214_p2(17 downto 17);
                tmp_51_reg_2162 <= tx_13_fu_1500_p3(16 downto 15);
                tmp_52_reg_2167 <= ty_13_fu_1508_p3(16 downto 15);
                tmp_9_reg_1930 <= tx_2_fu_578_p3(16 downto 4);
                tmp_reg_1808 <= tmp_fu_162_p1(16 downto 16);
                tmp_reg_1808_pp0_iter1_reg <= tmp_reg_1808;
                tmp_reg_1808_pp0_iter2_reg <= tmp_reg_1808_pp0_iter1_reg;
                trunc_ln98_3_reg_1935 <= ty_2_fu_585_p3(16 downto 4);
                tx_10_reg_2070 <= tx_10_fu_1218_p3;
                tx_13_reg_2145 <= tx_13_fu_1500_p3;
                tx_2_reg_1918 <= tx_2_fu_578_p3;
                tx_6_reg_1994 <= tx_6_fu_898_p3;
                ty_10_reg_2076 <= ty_10_fu_1225_p3;
                ty_13_reg_2151 <= ty_13_fu_1508_p3;
                ty_2_reg_1924 <= ty_2_fu_585_p3;
                ty_6_reg_2000 <= ty_6_fu_905_p3;
                tz_11_reg_2082 <= tz_11_fu_1244_p2;
                tz_13_reg_2140 <= tz_13_fu_1460_p2;
                tz_1_reg_1822 <= tz_1_fu_214_p2;
                tz_3_reg_1854 <= tz_3_fu_282_p2;
                tz_5_reg_1886 <= tz_5_fu_350_p2;
                tz_7_reg_1940 <= tz_7_fu_624_p2;
                tz_9_reg_2016 <= tz_9_fu_944_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to6, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start = ap_const_logic_0) and (ap_idle_pp0_1to6 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_reset_idle_pp0 = ap_const_logic_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_reset_idle_pp0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln102_10_fu_1292_p2 <= std_logic_vector(unsigned(tx_10_reg_2070) + unsigned(sext_ln84_15_fu_1289_p1));
    add_ln102_11_fu_1380_p2 <= std_logic_vector(unsigned(tx_11_fu_1312_p3) + unsigned(sext_ln84_17_fu_1376_p1));
    add_ln102_12_fu_1480_p2 <= std_logic_vector(unsigned(tx_12_reg_2113) + unsigned(sext_ln84_19_fu_1477_p1));
    add_ln102_13_fu_1576_p2 <= std_logic_vector(unsigned(tx_13_reg_2145) + unsigned(sext_ln84_21_fu_1573_p1));
    add_ln102_14_fu_1618_p2 <= std_logic_vector(unsigned(add_ln102_13_fu_1576_p2) + unsigned(select_ln84_1_fu_1610_p3));
    add_ln102_15_fu_1662_p2 <= std_logic_vector(unsigned(add_ln102_14_fu_1618_p2) + unsigned(select_ln84_3_fu_1654_p3));
    add_ln102_1_fu_554_p2 <= std_logic_vector(unsigned(zext_ln94_1_fu_515_p1) + unsigned(sext_ln102_1_fu_550_p1));
    add_ln102_2_fu_652_p2 <= std_logic_vector(unsigned(tx_2_reg_1918) + unsigned(sext_ln102_2_fu_649_p1));
    add_ln102_3_fu_714_p2 <= std_logic_vector(unsigned(tx_3_fu_672_p3) + unsigned(sext_ln102_3_fu_710_p1));
    add_ln102_4_fu_812_p2 <= std_logic_vector(unsigned(tx_4_reg_1956) + unsigned(sext_ln84_3_fu_809_p1));
    add_ln102_5_fu_874_p2 <= std_logic_vector(unsigned(tx_5_fu_832_p3) + unsigned(sext_ln84_5_fu_870_p1));
    add_ln102_6_fu_972_p2 <= std_logic_vector(unsigned(tx_6_reg_1994) + unsigned(sext_ln84_7_fu_969_p1));
    add_ln102_7_fu_1034_p2 <= std_logic_vector(unsigned(tx_7_fu_992_p3) + unsigned(sext_ln84_9_fu_1030_p1));
    add_ln102_8_fu_1132_p2 <= std_logic_vector(unsigned(tx_8_reg_2032) + unsigned(sext_ln84_11_fu_1129_p1));
    add_ln102_9_fu_1194_p2 <= std_logic_vector(unsigned(tx_9_fu_1152_p3) + unsigned(sext_ln84_13_fu_1190_p1));
    add_ln102_fu_484_p2 <= std_logic_vector(unsigned(zext_ln94_fu_441_p1) + unsigned(sext_ln102_fu_480_p1));
    add_ln108_10_fu_1307_p2 <= std_logic_vector(unsigned(ty_10_reg_2076) + unsigned(sext_ln84_14_fu_1286_p1));
    add_ln108_11_fu_1398_p2 <= std_logic_vector(unsigned(ty_11_fu_1319_p3) + unsigned(sext_ln84_16_fu_1362_p1));
    add_ln108_12_fu_1495_p2 <= std_logic_vector(unsigned(ty_12_reg_2119) + unsigned(sext_ln84_18_fu_1474_p1));
    add_ln108_13_fu_1679_p2 <= std_logic_vector(unsigned(ty_13_reg_2151) + unsigned(sext_ln84_20_fu_1570_p1));
    add_ln108_14_fu_1722_p2 <= std_logic_vector(unsigned(add_ln108_13_fu_1679_p2) + unsigned(select_ln98_fu_1692_p3));
    add_ln108_15_fu_1766_p2 <= std_logic_vector(unsigned(add_ln108_14_fu_1722_p2) + unsigned(select_ln98_1_fu_1736_p3));
    add_ln108_1_fu_572_p2 <= std_logic_vector(unsigned(ty_1_fu_519_p3) + unsigned(zext_ln84_1_fu_536_p1));
    add_ln108_2_fu_667_p2 <= std_logic_vector(unsigned(ty_2_reg_1924) + unsigned(sext_ln84_fu_646_p1));
    add_ln108_3_fu_732_p2 <= std_logic_vector(unsigned(ty_3_fu_679_p3) + unsigned(sext_ln84_1_fu_696_p1));
    add_ln108_4_fu_827_p2 <= std_logic_vector(unsigned(ty_4_reg_1962) + unsigned(sext_ln84_2_fu_806_p1));
    add_ln108_5_fu_892_p2 <= std_logic_vector(unsigned(ty_5_fu_839_p3) + unsigned(sext_ln84_4_fu_856_p1));
    add_ln108_6_fu_987_p2 <= std_logic_vector(unsigned(ty_6_reg_2000) + unsigned(sext_ln84_6_fu_966_p1));
    add_ln108_7_fu_1052_p2 <= std_logic_vector(unsigned(ty_7_fu_999_p3) + unsigned(sext_ln84_8_fu_1016_p1));
    add_ln108_8_fu_1147_p2 <= std_logic_vector(unsigned(ty_8_reg_2038) + unsigned(sext_ln84_10_fu_1126_p1));
    add_ln108_9_fu_1212_p2 <= std_logic_vector(unsigned(ty_9_fu_1159_p3) + unsigned(sext_ln84_12_fu_1176_p1));
    add_ln108_fu_502_p2 <= std_logic_vector(signed(sext_ln94_fu_452_p1) + signed(zext_ln84_fu_466_p1));
    add_ln94_10_fu_379_p2 <= std_logic_vector(unsigned(tz_5_reg_1886) + unsigned(ap_const_lv18_3FE01));
    add_ln94_12_fu_619_p2 <= std_logic_vector(unsigned(tz_6_reg_1902) + unsigned(ap_const_lv18_3FF01));
    add_ln94_14_fu_779_p2 <= std_logic_vector(unsigned(tz_7_reg_1940) + unsigned(ap_const_lv18_3FF81));
    add_ln94_16_fu_939_p2 <= std_logic_vector(unsigned(tz_8_reg_1978) + unsigned(ap_const_lv18_3FFC1));
    add_ln94_18_fu_1099_p2 <= std_logic_vector(unsigned(tz_9_reg_2016) + unsigned(ap_const_lv18_3FFE1));
    add_ln94_20_fu_1239_p2 <= std_logic_vector(unsigned(tz_10_reg_2054) + unsigned(ap_const_lv18_3FFF1));
    add_ln94_22_fu_1333_p2 <= std_logic_vector(unsigned(tz_11_reg_2082) + unsigned(ap_const_lv18_3FFF9));
    add_ln94_24_fu_1455_p2 <= std_logic_vector(unsigned(tz_12_reg_2108) + unsigned(ap_const_lv18_3FFFD));
    add_ln94_26_fu_1551_p2 <= std_logic_vector(unsigned(tz_13_reg_2140) + unsigned(ap_const_lv18_3FFFF));
    add_ln94_2_fu_243_p2 <= std_logic_vector(unsigned(tz_1_reg_1822) + unsigned(ap_const_lv18_3E0A5));
    add_ln94_4_fu_277_p2 <= std_logic_vector(unsigned(tz_2_reg_1838) + unsigned(ap_const_lv18_3F016));
    add_ln94_6_fu_311_p2 <= std_logic_vector(unsigned(tz_3_reg_1854) + unsigned(ap_const_lv18_3F803));
    add_ln94_8_fu_345_p2 <= std_logic_vector(unsigned(tz_4_reg_1870) + unsigned(ap_const_lv18_3FC01));
    add_ln94_fu_208_p2 <= std_logic_vector(unsigned(tz_fu_178_p2) + unsigned(ap_const_lv18_3C4A8));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage1_subdone <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_state10_pp0_stage1_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage1_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage1_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage1_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage1_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_enable_reg_pp0_iter6, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to5_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to5 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to6_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to6 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to6 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to5)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to5 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= sext_ln94_1_fu_1780_p1;
    ap_return_1 <= sext_ln83_fu_1792_p1;
    d_12_fu_1344_p3 <= tz_12_fu_1338_p2(17 downto 17);
    d_13_fu_1466_p3 <= tz_13_fu_1460_p2(17 downto 17);
    d_14_fu_1562_p3 <= tz_14_fu_1556_p2(17 downto 17);
    select_ln101_fu_170_p3 <= 
        ap_const_lv18_6487 when (tmp_fu_162_p3(0) = '1') else 
        ap_const_lv18_39B79;
    select_ln102_fu_406_p3 <= 
        ap_const_lv15_26DD when (tmp_reg_1808_pp0_iter2_reg(0) = '1') else 
        ap_const_lv15_7497;
    select_ln103_fu_413_p3 <= 
        ap_const_lv16_8B69 when (tmp_reg_1808_pp0_iter2_reg(0) = '1') else 
        ap_const_lv16_26DD;
    select_ln107_1_fu_1708_p3 <= 
        ap_const_lv17_1FFFF when (tmp_58_fu_1700_p3(0) = '1') else 
        ap_const_lv17_0;
    select_ln107_2_fu_1752_p3 <= 
        ap_const_lv17_1FFFF when (y_s_fu_1744_p3(0) = '1') else 
        ap_const_lv17_0;
    select_ln107_fu_420_p3 <= 
        ap_const_lv15_7497 when (tmp_reg_1808_pp0_iter2_reg(0) = '1') else 
        ap_const_lv15_26DD;
    select_ln108_fu_427_p3 <= 
        ap_const_lv16_D923 when (tmp_reg_1808_pp0_iter2_reg(0) = '1') else 
        ap_const_lv16_7497;
    select_ln84_1_fu_1610_p3 <= 
        ap_const_lv17_1FFFF when (tmp_54_fu_1602_p3(0) = '1') else 
        ap_const_lv17_0;
    select_ln84_2_fu_1638_p3 <= 
        ap_const_lv17_1FFFF when (tmp_55_fu_1630_p3(0) = '1') else 
        ap_const_lv17_0;
    select_ln84_3_fu_1654_p3 <= 
        ap_const_lv17_1FFFF when (tmp_56_fu_1646_p3(0) = '1') else 
        ap_const_lv17_0;
    select_ln84_fu_1594_p3 <= 
        ap_const_lv17_1FFFF when (tmp_53_fu_1586_p3(0) = '1') else 
        ap_const_lv17_0;
    select_ln94_11_fu_372_p3 <= 
        ap_const_lv18_3FE when (tmp_17_reg_1897(0) = '1') else 
        ap_const_lv18_0;
    select_ln94_13_fu_612_p3 <= 
        ap_const_lv18_1FE when (tmp_21_reg_1913(0) = '1') else 
        ap_const_lv18_0;
    select_ln94_15_fu_772_p3 <= 
        ap_const_lv18_FE when (tmp_25_reg_1951(0) = '1') else 
        ap_const_lv18_0;
    select_ln94_17_fu_932_p3 <= 
        ap_const_lv18_7E when (tmp_29_reg_1989(0) = '1') else 
        ap_const_lv18_0;
    select_ln94_19_fu_1092_p3 <= 
        ap_const_lv18_3E when (tmp_33_reg_2027(0) = '1') else 
        ap_const_lv18_0;
    select_ln94_1_fu_200_p3 <= 
        ap_const_lv18_76B0 when (tmp_2_fu_192_p3(0) = '1') else 
        ap_const_lv18_0;
    select_ln94_21_fu_1232_p3 <= 
        ap_const_lv18_1E when (tmp_37_reg_2065(0) = '1') else 
        ap_const_lv18_0;
    select_ln94_23_fu_1326_p3 <= 
        ap_const_lv18_E when (tmp_41_reg_2103(0) = '1') else 
        ap_const_lv18_0;
    select_ln94_25_fu_1448_p3 <= 
        ap_const_lv18_6 when (tmp_45_reg_2125(0) = '1') else 
        ap_const_lv18_0;
    select_ln94_27_fu_1544_p3 <= 
        ap_const_lv18_2 when (tmp_49_reg_2157(0) = '1') else 
        ap_const_lv18_0;
    select_ln94_3_fu_236_p3 <= 
        ap_const_lv18_3EB6 when (tmp_4_reg_1833(0) = '1') else 
        ap_const_lv18_0;
    select_ln94_5_fu_270_p3 <= 
        ap_const_lv18_1FD4 when (tmp_7_reg_1849(0) = '1') else 
        ap_const_lv18_0;
    select_ln94_7_fu_304_p3 <= 
        ap_const_lv18_FFA when (tmp_10_reg_1865(0) = '1') else 
        ap_const_lv18_0;
    select_ln94_9_fu_338_p3 <= 
        ap_const_lv18_7FE when (tmp_13_reg_1881(0) = '1') else 
        ap_const_lv18_0;
    select_ln98_1_fu_1736_p3 <= 
        ap_const_lv17_1FFFF when (x_s_1_fu_1728_p3(0) = '1') else 
        ap_const_lv17_0;
    select_ln98_fu_1692_p3 <= 
        ap_const_lv17_1FFFF when (tmp_57_fu_1684_p3(0) = '1') else 
        ap_const_lv17_0;
        sext_ln102_1_fu_550_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln98_2_fu_540_p4),17));

        sext_ln102_2_fu_649_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln98_3_reg_1935),17));

        sext_ln102_3_fu_710_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln98_4_fu_700_p4),17));

        sext_ln102_fu_480_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln98_1_fu_470_p4),16));

    sext_ln79_fu_158_p0 <= z_read;
        sext_ln79_fu_158_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln79_fu_158_p0),18));

        sext_ln83_fu_1792_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ty_14_fu_1784_p3),18));

        sext_ln84_10_fu_1126_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_31_reg_2044),17));

        sext_ln84_11_fu_1129_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_32_reg_2049),17));

        sext_ln84_12_fu_1176_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_35_fu_1166_p4),17));

        sext_ln84_13_fu_1190_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_36_fu_1180_p4),17));

        sext_ln84_14_fu_1286_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_39_reg_2093),17));

        sext_ln84_15_fu_1289_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_40_reg_2098),17));

        sext_ln84_16_fu_1362_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_43_fu_1352_p4),17));

        sext_ln84_17_fu_1376_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_44_fu_1366_p4),17));

        sext_ln84_18_fu_1474_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_47_reg_2130),17));

        sext_ln84_19_fu_1477_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_48_reg_2135),17));

        sext_ln84_1_fu_696_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_12_fu_686_p4),17));

        sext_ln84_20_fu_1570_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_51_reg_2162),17));

        sext_ln84_21_fu_1573_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_52_reg_2167),17));

        sext_ln84_2_fu_806_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_15_reg_1968),17));

        sext_ln84_3_fu_809_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_16_reg_1973),17));

        sext_ln84_4_fu_856_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_19_fu_846_p4),17));

        sext_ln84_5_fu_870_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_20_fu_860_p4),17));

        sext_ln84_6_fu_966_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_23_reg_2006),17));

        sext_ln84_7_fu_969_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_24_reg_2011),17));

        sext_ln84_8_fu_1016_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_27_fu_1006_p4),17));

        sext_ln84_9_fu_1030_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_28_fu_1020_p4),17));

        sext_ln84_fu_646_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_9_reg_1930),17));

        sext_ln94_1_fu_1780_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tx_14_fu_1772_p3),18));

        sext_ln94_fu_452_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ty_fu_445_p3),17));

    sub_ln103_10_fu_1297_p2 <= std_logic_vector(unsigned(ty_10_reg_2076) - unsigned(sext_ln84_14_fu_1286_p1));
    sub_ln103_11_fu_1386_p2 <= std_logic_vector(unsigned(ty_11_fu_1319_p3) - unsigned(sext_ln84_16_fu_1362_p1));
    sub_ln103_12_fu_1485_p2 <= std_logic_vector(unsigned(ty_12_reg_2119) - unsigned(sext_ln84_18_fu_1474_p1));
    sub_ln103_13_fu_1581_p2 <= std_logic_vector(unsigned(ty_13_reg_2151) - unsigned(sext_ln84_20_fu_1570_p1));
    sub_ln103_14_fu_1624_p2 <= std_logic_vector(unsigned(sub_ln103_13_fu_1581_p2) - unsigned(select_ln84_fu_1594_p3));
    sub_ln103_15_fu_1668_p2 <= std_logic_vector(unsigned(sub_ln103_14_fu_1624_p2) - unsigned(select_ln84_2_fu_1638_p3));
    sub_ln103_1_fu_560_p2 <= std_logic_vector(unsigned(ty_1_fu_519_p3) - unsigned(zext_ln84_1_fu_536_p1));
    sub_ln103_2_fu_657_p2 <= std_logic_vector(unsigned(ty_2_reg_1924) - unsigned(sext_ln84_fu_646_p1));
    sub_ln103_3_fu_720_p2 <= std_logic_vector(unsigned(ty_3_fu_679_p3) - unsigned(sext_ln84_1_fu_696_p1));
    sub_ln103_4_fu_817_p2 <= std_logic_vector(unsigned(ty_4_reg_1962) - unsigned(sext_ln84_2_fu_806_p1));
    sub_ln103_5_fu_880_p2 <= std_logic_vector(unsigned(ty_5_fu_839_p3) - unsigned(sext_ln84_4_fu_856_p1));
    sub_ln103_6_fu_977_p2 <= std_logic_vector(unsigned(ty_6_reg_2000) - unsigned(sext_ln84_6_fu_966_p1));
    sub_ln103_7_fu_1040_p2 <= std_logic_vector(unsigned(ty_7_fu_999_p3) - unsigned(sext_ln84_8_fu_1016_p1));
    sub_ln103_8_fu_1137_p2 <= std_logic_vector(unsigned(ty_8_reg_2038) - unsigned(sext_ln84_10_fu_1126_p1));
    sub_ln103_9_fu_1200_p2 <= std_logic_vector(unsigned(ty_9_fu_1159_p3) - unsigned(sext_ln84_12_fu_1176_p1));
    sub_ln103_fu_490_p2 <= std_logic_vector(signed(sext_ln94_fu_452_p1) - signed(zext_ln84_fu_466_p1));
    sub_ln107_10_fu_1302_p2 <= std_logic_vector(unsigned(tx_10_reg_2070) - unsigned(sext_ln84_15_fu_1289_p1));
    sub_ln107_11_fu_1392_p2 <= std_logic_vector(unsigned(tx_11_fu_1312_p3) - unsigned(sext_ln84_17_fu_1376_p1));
    sub_ln107_12_fu_1490_p2 <= std_logic_vector(unsigned(tx_12_reg_2113) - unsigned(sext_ln84_19_fu_1477_p1));
    sub_ln107_13_fu_1674_p2 <= std_logic_vector(unsigned(tx_13_reg_2145) - unsigned(sext_ln84_21_fu_1573_p1));
    sub_ln107_14_fu_1716_p2 <= std_logic_vector(unsigned(sub_ln107_13_fu_1674_p2) - unsigned(select_ln107_1_fu_1708_p3));
    sub_ln107_15_fu_1760_p2 <= std_logic_vector(unsigned(sub_ln107_14_fu_1716_p2) - unsigned(select_ln107_2_fu_1752_p3));
    sub_ln107_1_fu_566_p2 <= std_logic_vector(unsigned(zext_ln94_1_fu_515_p1) - unsigned(sext_ln102_1_fu_550_p1));
    sub_ln107_2_fu_662_p2 <= std_logic_vector(unsigned(tx_2_reg_1918) - unsigned(sext_ln102_2_fu_649_p1));
    sub_ln107_3_fu_726_p2 <= std_logic_vector(unsigned(tx_3_fu_672_p3) - unsigned(sext_ln102_3_fu_710_p1));
    sub_ln107_4_fu_822_p2 <= std_logic_vector(unsigned(tx_4_reg_1956) - unsigned(sext_ln84_3_fu_809_p1));
    sub_ln107_5_fu_886_p2 <= std_logic_vector(unsigned(tx_5_fu_832_p3) - unsigned(sext_ln84_5_fu_870_p1));
    sub_ln107_6_fu_982_p2 <= std_logic_vector(unsigned(tx_6_reg_1994) - unsigned(sext_ln84_7_fu_969_p1));
    sub_ln107_7_fu_1046_p2 <= std_logic_vector(unsigned(tx_7_fu_992_p3) - unsigned(sext_ln84_9_fu_1030_p1));
    sub_ln107_8_fu_1142_p2 <= std_logic_vector(unsigned(tx_8_reg_2032) - unsigned(sext_ln84_11_fu_1129_p1));
    sub_ln107_9_fu_1206_p2 <= std_logic_vector(unsigned(tx_9_fu_1152_p3) - unsigned(sext_ln84_13_fu_1190_p1));
    sub_ln107_fu_496_p2 <= std_logic_vector(unsigned(zext_ln94_fu_441_p1) - unsigned(sext_ln102_fu_480_p1));
    tmp_12_fu_686_p4 <= tx_3_fu_672_p3(16 downto 5);
    tmp_19_fu_846_p4 <= tx_5_fu_832_p3(16 downto 7);
    tmp_20_fu_860_p4 <= ty_5_fu_839_p3(16 downto 7);
    tmp_27_fu_1006_p4 <= tx_7_fu_992_p3(16 downto 9);
    tmp_28_fu_1020_p4 <= ty_7_fu_999_p3(16 downto 9);
    tmp_2_fu_192_p3 <= tz_fu_178_p2(17 downto 17);
    tmp_35_fu_1166_p4 <= tx_9_fu_1152_p3(16 downto 11);
    tmp_36_fu_1180_p4 <= ty_9_fu_1159_p3(16 downto 11);
    tmp_43_fu_1352_p4 <= tx_11_fu_1312_p3(16 downto 13);
    tmp_44_fu_1366_p4 <= ty_11_fu_1319_p3(16 downto 13);
    tmp_53_fu_1586_p3 <= add_ln102_13_fu_1576_p2(16 downto 16);
    tmp_54_fu_1602_p3 <= sub_ln103_13_fu_1581_p2(16 downto 16);
    tmp_55_fu_1630_p3 <= add_ln102_14_fu_1618_p2(16 downto 16);
    tmp_56_fu_1646_p3 <= sub_ln103_14_fu_1624_p2(16 downto 16);
    tmp_57_fu_1684_p3 <= sub_ln107_13_fu_1674_p2(16 downto 16);
    tmp_58_fu_1700_p3 <= add_ln108_13_fu_1679_p2(16 downto 16);
    tmp_6_fu_526_p4 <= tx_1_fu_508_p3(15 downto 3);
    tmp_fu_162_p1 <= z_read;
    tmp_fu_162_p3 <= tmp_fu_162_p1(16 downto 16);
    trunc_ln98_1_fu_470_p4 <= ty_fu_445_p3(15 downto 2);
    trunc_ln98_2_fu_540_p4 <= ty_1_fu_519_p3(16 downto 3);
    trunc_ln98_4_fu_700_p4 <= ty_3_fu_679_p3(16 downto 5);
    tx_10_fu_1218_p3 <= 
        add_ln102_9_fu_1194_p2 when (d_10_reg_2059(0) = '1') else 
        sub_ln107_9_fu_1206_p2;
    tx_11_fu_1312_p3 <= 
        add_ln102_10_fu_1292_p2 when (d_11_reg_2087(0) = '1') else 
        sub_ln107_10_fu_1302_p2;
    tx_12_fu_1404_p3 <= 
        add_ln102_11_fu_1380_p2 when (d_12_fu_1344_p3(0) = '1') else 
        sub_ln107_11_fu_1392_p2;
    tx_13_fu_1500_p3 <= 
        add_ln102_12_fu_1480_p2 when (d_13_fu_1466_p3(0) = '1') else 
        sub_ln107_12_fu_1490_p2;
    tx_14_fu_1772_p3 <= 
        add_ln102_15_fu_1662_p2 when (d_14_fu_1562_p3(0) = '1') else 
        sub_ln107_15_fu_1760_p2;
    tx_1_fu_508_p3 <= 
        add_ln102_fu_484_p2 when (d_1_reg_1827_pp0_iter2_reg(0) = '1') else 
        sub_ln107_fu_496_p2;
    tx_2_fu_578_p3 <= 
        add_ln102_1_fu_554_p2 when (d_2_reg_1843_pp0_iter2_reg(0) = '1') else 
        sub_ln107_1_fu_566_p2;
    tx_3_fu_672_p3 <= 
        add_ln102_2_fu_652_p2 when (d_3_reg_1859_pp0_iter3_reg(0) = '1') else 
        sub_ln107_2_fu_662_p2;
    tx_4_fu_738_p3 <= 
        add_ln102_3_fu_714_p2 when (d_4_reg_1875_pp0_iter2_reg(0) = '1') else 
        sub_ln107_3_fu_726_p2;
    tx_5_fu_832_p3 <= 
        add_ln102_4_fu_812_p2 when (d_5_reg_1891_pp0_iter3_reg(0) = '1') else 
        sub_ln107_4_fu_822_p2;
    tx_6_fu_898_p3 <= 
        add_ln102_5_fu_874_p2 when (d_6_reg_1907_pp0_iter3_reg(0) = '1') else 
        sub_ln107_5_fu_886_p2;
    tx_7_fu_992_p3 <= 
        add_ln102_6_fu_972_p2 when (d_7_reg_1945_pp0_iter4_reg(0) = '1') else 
        sub_ln107_6_fu_982_p2;
    tx_8_fu_1058_p3 <= 
        add_ln102_7_fu_1034_p2 when (d_8_reg_1983(0) = '1') else 
        sub_ln107_7_fu_1046_p2;
    tx_9_fu_1152_p3 <= 
        add_ln102_8_fu_1132_p2 when (d_9_reg_2021(0) = '1') else 
        sub_ln107_8_fu_1142_p2;
    tx_fu_434_p3 <= 
        select_ln102_fu_406_p3 when (d_reg_1816_pp0_iter2_reg(0) = '1') else 
        select_ln107_fu_420_p3;
    ty_10_fu_1225_p3 <= 
        sub_ln103_9_fu_1200_p2 when (d_10_reg_2059(0) = '1') else 
        add_ln108_9_fu_1212_p2;
    ty_11_fu_1319_p3 <= 
        sub_ln103_10_fu_1297_p2 when (d_11_reg_2087(0) = '1') else 
        add_ln108_10_fu_1307_p2;
    ty_12_fu_1412_p3 <= 
        sub_ln103_11_fu_1386_p2 when (d_12_fu_1344_p3(0) = '1') else 
        add_ln108_11_fu_1398_p2;
    ty_13_fu_1508_p3 <= 
        sub_ln103_12_fu_1485_p2 when (d_13_fu_1466_p3(0) = '1') else 
        add_ln108_12_fu_1495_p2;
    ty_14_fu_1784_p3 <= 
        sub_ln103_15_fu_1668_p2 when (d_14_fu_1562_p3(0) = '1') else 
        add_ln108_15_fu_1766_p2;
    ty_1_fu_519_p3 <= 
        sub_ln103_fu_490_p2 when (d_1_reg_1827_pp0_iter2_reg(0) = '1') else 
        add_ln108_fu_502_p2;
    ty_2_fu_585_p3 <= 
        sub_ln103_1_fu_560_p2 when (d_2_reg_1843_pp0_iter2_reg(0) = '1') else 
        add_ln108_1_fu_572_p2;
    ty_3_fu_679_p3 <= 
        sub_ln103_2_fu_657_p2 when (d_3_reg_1859_pp0_iter3_reg(0) = '1') else 
        add_ln108_2_fu_667_p2;
    ty_4_fu_745_p3 <= 
        sub_ln103_3_fu_720_p2 when (d_4_reg_1875_pp0_iter2_reg(0) = '1') else 
        add_ln108_3_fu_732_p2;
    ty_5_fu_839_p3 <= 
        sub_ln103_4_fu_817_p2 when (d_5_reg_1891_pp0_iter3_reg(0) = '1') else 
        add_ln108_4_fu_827_p2;
    ty_6_fu_905_p3 <= 
        sub_ln103_5_fu_880_p2 when (d_6_reg_1907_pp0_iter3_reg(0) = '1') else 
        add_ln108_5_fu_892_p2;
    ty_7_fu_999_p3 <= 
        sub_ln103_6_fu_977_p2 when (d_7_reg_1945_pp0_iter4_reg(0) = '1') else 
        add_ln108_6_fu_987_p2;
    ty_8_fu_1065_p3 <= 
        sub_ln103_7_fu_1040_p2 when (d_8_reg_1983(0) = '1') else 
        add_ln108_7_fu_1052_p2;
    ty_9_fu_1159_p3 <= 
        sub_ln103_8_fu_1137_p2 when (d_9_reg_2021(0) = '1') else 
        add_ln108_8_fu_1147_p2;
    ty_fu_445_p3 <= 
        select_ln103_fu_413_p3 when (d_reg_1816_pp0_iter2_reg(0) = '1') else 
        select_ln108_fu_427_p3;
    tz_10_fu_1104_p2 <= std_logic_vector(unsigned(add_ln94_18_fu_1099_p2) + unsigned(select_ln94_19_fu_1092_p3));
    tz_11_fu_1244_p2 <= std_logic_vector(unsigned(add_ln94_20_fu_1239_p2) + unsigned(select_ln94_21_fu_1232_p3));
    tz_12_fu_1338_p2 <= std_logic_vector(unsigned(add_ln94_22_fu_1333_p2) + unsigned(select_ln94_23_fu_1326_p3));
    tz_13_fu_1460_p2 <= std_logic_vector(unsigned(add_ln94_24_fu_1455_p2) + unsigned(select_ln94_25_fu_1448_p3));
    tz_14_fu_1556_p2 <= std_logic_vector(unsigned(add_ln94_26_fu_1551_p2) + unsigned(select_ln94_27_fu_1544_p3));
    tz_1_fu_214_p2 <= std_logic_vector(unsigned(add_ln94_fu_208_p2) + unsigned(select_ln94_1_fu_200_p3));
    tz_2_fu_248_p2 <= std_logic_vector(unsigned(add_ln94_2_fu_243_p2) + unsigned(select_ln94_3_fu_236_p3));
    tz_3_fu_282_p2 <= std_logic_vector(unsigned(add_ln94_4_fu_277_p2) + unsigned(select_ln94_5_fu_270_p3));
    tz_4_fu_316_p2 <= std_logic_vector(unsigned(add_ln94_6_fu_311_p2) + unsigned(select_ln94_7_fu_304_p3));
    tz_5_fu_350_p2 <= std_logic_vector(unsigned(add_ln94_8_fu_345_p2) + unsigned(select_ln94_9_fu_338_p3));
    tz_6_fu_384_p2 <= std_logic_vector(unsigned(add_ln94_10_fu_379_p2) + unsigned(select_ln94_11_fu_372_p3));
    tz_7_fu_624_p2 <= std_logic_vector(unsigned(add_ln94_12_fu_619_p2) + unsigned(select_ln94_13_fu_612_p3));
    tz_8_fu_784_p2 <= std_logic_vector(unsigned(add_ln94_14_fu_779_p2) + unsigned(select_ln94_15_fu_772_p3));
    tz_9_fu_944_p2 <= std_logic_vector(unsigned(add_ln94_16_fu_939_p2) + unsigned(select_ln94_17_fu_932_p3));
    tz_fu_178_p2 <= std_logic_vector(unsigned(select_ln101_fu_170_p3) + unsigned(sext_ln79_fu_158_p1));
    x_s_1_fu_1728_p3 <= sub_ln107_14_fu_1716_p2(16 downto 16);
    x_s_fu_456_p4 <= tx_fu_434_p3(14 downto 2);
    y_s_fu_1744_p3 <= add_ln108_14_fu_1722_p2(16 downto 16);
    zext_ln84_1_fu_536_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_526_p4),17));
    zext_ln84_fu_466_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_s_fu_456_p4),17));
    zext_ln94_1_fu_515_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tx_1_fu_508_p3),17));
    zext_ln94_fu_441_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tx_fu_434_p3),16));
end behav;
