-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft32_generic_sincos_16_4_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (13 downto 0) );
end;


architecture behav of fft32_generic_sincos_16_4_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv37_145F30 : STD_LOGIC_VECTOR (36 downto 0) := "0000000000000000101000101111100110000";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv18_1921F : STD_LOGIC_VECTOR (17 downto 0) := "011001001000011111";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv18_DBC1 : STD_LOGIC_VECTOR (17 downto 0) := "001101101111000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal sign0_fu_85_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_reg_374 : STD_LOGIC_VECTOR (0 downto 0);
    signal inabs_fu_97_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal inabs_reg_379 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln68_fu_105_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln68_reg_384 : STD_LOGIC_VECTOR (12 downto 0);
    signal kint_reg_389 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal k_reg_394 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal icmp_ln251_1_fu_172_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln251_1_reg_412 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal z_fu_206_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal z_reg_418 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_ap_start : STD_LOGIC;
    signal grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_ap_done : STD_LOGIC;
    signal grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_ap_idle : STD_LOGIC;
    signal grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_ap_ready : STD_LOGIC;
    signal grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_p_out : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_p_out_ap_vld : STD_LOGIC;
    signal grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_p_out1 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_p_out1_ap_vld : STD_LOGIC;
    signal grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal p_loc_fu_66 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_loc2_fu_62 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal sub_ln237_fu_91_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln64_fu_112_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln64_fu_112_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal mul_ln64_fu_112_p2 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_fu_352_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal r_fu_148_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln68_1_fu_157_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal icmp_ln251_fu_167_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_183_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln254_fu_161_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal or_ln251_fu_177_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_196_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln254_fu_192_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln280_fu_241_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln274_fu_257_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln2_fu_231_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln274_1_fu_263_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln274_fu_280_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln274_fu_273_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln1_fu_221_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln3_fu_247_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln274_1_fu_293_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln274_fu_306_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln274_2_fu_298_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln274_3_fu_311_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln274_1_fu_285_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal sub_ln292_fu_327_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln291_fu_333_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln274_4_fu_319_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_352_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_352_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_352_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal grp_fu_352_p00 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln64_fu_112_p00 : STD_LOGIC_VECTOR (36 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component fft32_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        z : IN STD_LOGIC_VECTOR (16 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (16 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        p_out1 : OUT STD_LOGIC_VECTOR (16 downto 0);
        p_out1_ap_vld : OUT STD_LOGIC );
    end component;


    component fft32_mul_16ns_22ns_37_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (21 downto 0);
        dout : OUT STD_LOGIC_VECTOR (36 downto 0) );
    end component;


    component fft32_mac_muladd_4ns_16ns_18ns_18_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (17 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;



begin
    grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76 : component fft32_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_ap_start,
        ap_done => grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_ap_done,
        ap_idle => grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_ap_idle,
        ap_ready => grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_ap_ready,
        z => z_reg_418,
        p_out => grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_p_out,
        p_out_ap_vld => grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_p_out_ap_vld,
        p_out1 => grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_p_out1,
        p_out1_ap_vld => grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_p_out1_ap_vld);

    mul_16ns_22ns_37_1_1_U344 : component fft32_mul_16ns_22ns_37_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 22,
        dout_WIDTH => 37)
    port map (
        din0 => mul_ln64_fu_112_p0,
        din1 => mul_ln64_fu_112_p1,
        dout => mul_ln64_fu_112_p2);

    mac_muladd_4ns_16ns_18ns_18_4_1_U345 : component fft32_mac_muladd_4ns_16ns_18ns_18_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 4,
        din1_WIDTH => 16,
        din2_WIDTH => 18,
        dout_WIDTH => 18)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_352_p0,
        din1 => grp_fu_352_p1,
        din2 => grp_fu_352_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_352_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_ap_ready = ap_const_logic_1)) then 
                    grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                icmp_ln251_1_reg_412 <= icmp_ln251_1_fu_172_p2;
                z_reg_418 <= z_fu_206_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                inabs_reg_379 <= inabs_fu_97_p3;
                sign0_reg_374 <= sign0_fu_85_p2;
                trunc_ln68_reg_384 <= trunc_ln68_fu_105_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                k_reg_394 <= mul_ln64_fu_112_p2(34 downto 33);
                kint_reg_389 <= mul_ln64_fu_112_p2(36 downto 33);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_p_out1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                p_loc2_fu_62 <= grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_p_out1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_p_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                p_loc_fu_66 <= grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_p_out;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_ap_done, ap_CS_fsm_state7)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_ap_done)
    begin
        if ((grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= select_ln291_fu_333_p3;
    ap_return_1 <= select_ln274_4_fu_319_p3;
    grp_fu_352_p0 <= grp_fu_352_p00(4 - 1 downto 0);
    grp_fu_352_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kint_reg_389),18));
    grp_fu_352_p1 <= ap_const_lv18_DBC1(16 - 1 downto 0);
    grp_fu_352_p2 <= (trunc_ln68_reg_384 & ap_const_lv5_0);
    grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_ap_start <= grp_generic_sincos_16_4_Pipeline_VITIS_LOOP_87_1_fu_76_ap_start_reg;
    icmp_ln251_1_fu_172_p2 <= "1" when (k_reg_394 = ap_const_lv2_1) else "0";
    icmp_ln251_fu_167_p2 <= "1" when (k_reg_394 = ap_const_lv2_3) else "0";
    icmp_ln274_1_fu_293_p2 <= "1" when (k_reg_394 = ap_const_lv2_2) else "0";
    icmp_ln274_fu_280_p2 <= "1" when (k_reg_394 = ap_const_lv2_0) else "0";
    inabs_fu_97_p3 <= 
        in_val when (sign0_fu_85_p2(0) = '1') else 
        sub_ln237_fu_91_p2;
    mul_ln64_fu_112_p0 <= mul_ln64_fu_112_p00(16 - 1 downto 0);
    mul_ln64_fu_112_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(inabs_reg_379),37));
    mul_ln64_fu_112_p1 <= ap_const_lv37_145F30(22 - 1 downto 0);
    or_ln251_fu_177_p2 <= (icmp_ln251_fu_167_p2 or icmp_ln251_1_fu_172_p2);
    or_ln274_fu_306_p2 <= (icmp_ln274_fu_280_p2 or icmp_ln251_1_reg_412);
    r_fu_148_p4 <= grp_fu_352_p3(17 downto 1);
    select_ln274_1_fu_285_p3 <= 
        trunc_ln2_fu_231_p4 when (icmp_ln274_fu_280_p2(0) = '1') else 
        select_ln274_fu_273_p3;
    select_ln274_2_fu_298_p3 <= 
        trunc_ln1_fu_221_p4 when (icmp_ln274_fu_280_p2(0) = '1') else 
        trunc_ln3_fu_247_p4;
    select_ln274_3_fu_311_p3 <= 
        trunc_ln3_fu_247_p4 when (icmp_ln274_1_fu_293_p2(0) = '1') else 
        trunc_ln1_fu_221_p4;
    select_ln274_4_fu_319_p3 <= 
        select_ln274_2_fu_298_p3 when (or_ln274_fu_306_p2(0) = '1') else 
        select_ln274_3_fu_311_p3;
    select_ln274_fu_273_p3 <= 
        trunc_ln2_fu_231_p4 when (icmp_ln251_1_reg_412(0) = '1') else 
        trunc_ln274_1_fu_263_p4;
    select_ln291_fu_333_p3 <= 
        select_ln274_1_fu_285_p3 when (sign0_reg_374(0) = '1') else 
        sub_ln292_fu_327_p2;
    sign0_fu_85_p2 <= "1" when (signed(in_val) > signed(ap_const_lv16_0)) else "0";
    sub_ln237_fu_91_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(in_val));
    sub_ln254_fu_161_p2 <= std_logic_vector(unsigned(ap_const_lv18_1921F) - unsigned(zext_ln68_1_fu_157_p1));
    sub_ln274_fu_257_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(p_loc_fu_66));
    sub_ln280_fu_241_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(p_loc2_fu_62));
    sub_ln292_fu_327_p2 <= std_logic_vector(unsigned(ap_const_lv14_0) - unsigned(select_ln274_1_fu_285_p3));
    tmp_1_fu_183_p4 <= grp_fu_352_p3(17 downto 2);
    tmp_2_fu_196_p4 <= sub_ln254_fu_161_p2(17 downto 1);
    trunc_ln1_fu_221_p4 <= p_loc2_fu_62(16 downto 3);
    trunc_ln274_1_fu_263_p4 <= sub_ln274_fu_257_p2(16 downto 3);
    trunc_ln2_fu_231_p4 <= p_loc_fu_66(16 downto 3);
    trunc_ln3_fu_247_p4 <= sub_ln280_fu_241_p2(16 downto 3);
    trunc_ln68_fu_105_p1 <= inabs_fu_97_p3(13 - 1 downto 0);
    z_fu_206_p3 <= 
        tmp_2_fu_196_p4 when (or_ln251_fu_177_p2(0) = '1') else 
        zext_ln254_fu_192_p1;
    zext_ln254_fu_192_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_183_p4),17));
    zext_ln68_1_fu_157_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_fu_148_p4),18));
end behav;
