-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft32_fft32_Pipeline_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    select_ln18_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    select_ln18_out_ap_vld : OUT STD_LOGIC;
    select_ln18_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    select_ln18_1_out_ap_vld : OUT STD_LOGIC;
    select_ln18_2_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    select_ln18_2_out_ap_vld : OUT STD_LOGIC;
    select_ln18_3_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    select_ln18_3_out_ap_vld : OUT STD_LOGIC;
    select_ln18_4_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    select_ln18_4_out_ap_vld : OUT STD_LOGIC;
    select_ln18_5_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    select_ln18_5_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of fft32_fft32_Pipeline_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln114_fu_126_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal select_ln18_1_fu_94_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln18_2_fu_102_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln18_4_fu_110_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln18_5_fu_118_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal phi_ln114_fu_36 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln114_fu_76_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_phi_ln114_load : STD_LOGIC_VECTOR (1 downto 0);
    signal w_real_1_0_fu_40 : STD_LOGIC_VECTOR (15 downto 0);
    signal w_real_2_0_fu_44 : STD_LOGIC_VECTOR (15 downto 0);
    signal w_imag_1_0_fu_48 : STD_LOGIC_VECTOR (15 downto 0);
    signal w_imag_2_0_fu_52 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln18_2_fu_88_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_1_fu_82_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fft32_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component fft32_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    phi_ln114_fu_36_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then
                phi_ln114_fu_36 <= add_ln114_fu_76_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then
                w_imag_1_0_fu_48 <= select_ln18_5_fu_118_p3;
                w_imag_2_0_fu_52 <= select_ln18_4_fu_110_p3;
                w_real_1_0_fu_40 <= select_ln18_2_fu_102_p3;
                w_real_2_0_fu_44 <= select_ln18_1_fu_94_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln114_fu_76_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_ln114_load) + unsigned(ap_const_lv2_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start_int)
    begin
        if ((ap_start_int = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, icmp_ln114_fu_126_p2, ap_start_int)
    begin
        if (((icmp_ln114_fu_126_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_phi_ln114_load_assign_proc : process(ap_CS_fsm_state1, phi_ln114_fu_36, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_phi_ln114_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_phi_ln114_load <= phi_ln114_fu_36;
        end if; 
    end process;

    icmp_ln114_fu_126_p2 <= "1" when (ap_sig_allocacmp_phi_ln114_load = ap_const_lv2_3) else "0";
    icmp_ln18_1_fu_82_p2 <= "1" when (ap_sig_allocacmp_phi_ln114_load = ap_const_lv2_1) else "0";
    icmp_ln18_2_fu_88_p2 <= "1" when (ap_sig_allocacmp_phi_ln114_load = ap_const_lv2_2) else "0";
    select_ln18_1_fu_94_p3 <= 
        ap_const_lv16_0 when (icmp_ln18_2_fu_88_p2(0) = '1') else 
        w_real_2_0_fu_44;
    select_ln18_1_out <= 
        ap_const_lv16_0 when (icmp_ln18_2_fu_88_p2(0) = '1') else 
        w_real_2_0_fu_44;

    select_ln18_1_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln114_fu_126_p2, ap_start_int)
    begin
        if (((icmp_ln114_fu_126_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            select_ln18_1_out_ap_vld <= ap_const_logic_1;
        else 
            select_ln18_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln18_2_fu_102_p3 <= 
        ap_const_lv16_0 when (icmp_ln18_1_fu_82_p2(0) = '1') else 
        w_real_1_0_fu_40;
    select_ln18_2_out <= 
        ap_const_lv16_0 when (icmp_ln18_1_fu_82_p2(0) = '1') else 
        w_real_1_0_fu_40;

    select_ln18_2_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln114_fu_126_p2, ap_start_int)
    begin
        if (((icmp_ln114_fu_126_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            select_ln18_2_out_ap_vld <= ap_const_logic_1;
        else 
            select_ln18_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln18_3_out <= ap_const_lv16_0;

    select_ln18_3_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln114_fu_126_p2, ap_start_int)
    begin
        if (((icmp_ln114_fu_126_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            select_ln18_3_out_ap_vld <= ap_const_logic_1;
        else 
            select_ln18_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln18_4_fu_110_p3 <= 
        ap_const_lv16_0 when (icmp_ln18_2_fu_88_p2(0) = '1') else 
        w_imag_2_0_fu_52;
    select_ln18_4_out <= 
        ap_const_lv16_0 when (icmp_ln18_2_fu_88_p2(0) = '1') else 
        w_imag_2_0_fu_52;

    select_ln18_4_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln114_fu_126_p2, ap_start_int)
    begin
        if (((icmp_ln114_fu_126_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            select_ln18_4_out_ap_vld <= ap_const_logic_1;
        else 
            select_ln18_4_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln18_5_fu_118_p3 <= 
        ap_const_lv16_0 when (icmp_ln18_1_fu_82_p2(0) = '1') else 
        w_imag_1_0_fu_48;
    select_ln18_5_out <= 
        ap_const_lv16_0 when (icmp_ln18_1_fu_82_p2(0) = '1') else 
        w_imag_1_0_fu_48;

    select_ln18_5_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln114_fu_126_p2, ap_start_int)
    begin
        if (((icmp_ln114_fu_126_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            select_ln18_5_out_ap_vld <= ap_const_logic_1;
        else 
            select_ln18_5_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln18_out <= ap_const_lv16_0;

    select_ln18_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln114_fu_126_p2, ap_start_int)
    begin
        if (((icmp_ln114_fu_126_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            select_ln18_out_ap_vld <= ap_const_logic_1;
        else 
            select_ln18_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
