// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fft32_radix4_bfly_1 (
        ap_ready,
        a_real_read,
        a_imag_read,
        b_real_read,
        b_imag_read,
        c_real_read,
        c_imag_read,
        d_real_read,
        d_imag_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7
);


output   ap_ready;
input  [15:0] a_real_read;
input  [15:0] a_imag_read;
input  [15:0] b_real_read;
input  [15:0] b_imag_read;
input  [15:0] c_real_read;
input  [15:0] c_imag_read;
input  [15:0] d_real_read;
input  [15:0] d_imag_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;

wire   [15:0] cr0_fu_92_p2;
wire   [15:0] ar0_fu_68_p2;
wire   [15:0] ci0_fu_98_p2;
wire   [15:0] ai0_fu_74_p2;
wire   [15:0] ci1_fu_110_p2;
wire   [15:0] ar1_fu_80_p2;
wire   [15:0] ai1_fu_86_p2;
wire   [15:0] cr1_fu_104_p2;
wire   [15:0] add_ln34_fu_116_p2;
wire   [15:0] add_ln34_1_fu_122_p2;
wire   [15:0] add_ln35_fu_128_p2;
wire   [15:0] sub_ln35_fu_134_p2;
wire   [15:0] sub_ln36_fu_140_p2;
wire   [15:0] sub_ln36_1_fu_146_p2;
wire   [15:0] sub_ln37_fu_152_p2;
wire   [15:0] add_ln37_fu_158_p2;

assign add_ln34_1_fu_122_p2 = (ci0_fu_98_p2 + ai0_fu_74_p2);

assign add_ln34_fu_116_p2 = (cr0_fu_92_p2 + ar0_fu_68_p2);

assign add_ln35_fu_128_p2 = (ci1_fu_110_p2 + ar1_fu_80_p2);

assign add_ln37_fu_158_p2 = (cr1_fu_104_p2 + ai1_fu_86_p2);

assign ai0_fu_74_p2 = (b_imag_read + a_imag_read);

assign ai1_fu_86_p2 = (a_imag_read - b_imag_read);

assign ap_ready = 1'b1;

assign ar0_fu_68_p2 = (b_real_read + a_real_read);

assign ar1_fu_80_p2 = (a_real_read - b_real_read);

assign ci0_fu_98_p2 = (d_imag_read + c_imag_read);

assign ci1_fu_110_p2 = (c_imag_read - d_imag_read);

assign cr0_fu_92_p2 = (d_real_read + c_real_read);

assign cr1_fu_104_p2 = (c_real_read - d_real_read);

assign sub_ln35_fu_134_p2 = (ai1_fu_86_p2 - cr1_fu_104_p2);

assign sub_ln36_1_fu_146_p2 = (ai0_fu_74_p2 - ci0_fu_98_p2);

assign sub_ln36_fu_140_p2 = (ar0_fu_68_p2 - cr0_fu_92_p2);

assign sub_ln37_fu_152_p2 = (ar1_fu_80_p2 - ci1_fu_110_p2);

assign ap_return_0 = add_ln34_fu_116_p2;

assign ap_return_1 = add_ln34_1_fu_122_p2;

assign ap_return_2 = add_ln35_fu_128_p2;

assign ap_return_3 = sub_ln35_fu_134_p2;

assign ap_return_4 = sub_ln36_fu_140_p2;

assign ap_return_5 = sub_ln36_1_fu_146_p2;

assign ap_return_6 = sub_ln37_fu_152_p2;

assign ap_return_7 = add_ln37_fu_158_p2;

endmodule //fft32_radix4_bfly_1
